-- ============================================================
-- SEED — AgendaFácil
-- Requer: migration aplicada (tabelas + trigger existem)
-- ============================================================
--
-- IMPORTANTE: o usuário `postgres` do Supabase NÃO é dono de
-- `auth.users`, então esta seed NÃO pode:
--   * ALTER TRIGGER em auth.users
--   * INSERT em auth.users
--   * DELETE em auth.users
--
-- Para popular dados de teste use o script JS complementar:
--
--   node scripts/seed.mjs
--
-- Ele usa a service role key para:
--   1. deletar o usuário teste@barbearia.com (se existir)
--   2. criar o usuário (o trigger handle_new_user gera salão
--      e dados padrão)
--   3. atualizar o salão com nome "Barbearia Teste"
--   4. substituir profissionais/serviços/agendamentos de exemplo
--
-- Requer variáveis no .env.local:
--   NEXT_PUBLIC_SUPABASE_URL
--   SUPABASE_SERVICE_KEY
-- ============================================================
SELECT 'use scripts/seed.mjs' AS notice;
