import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],

  theme: {
    extend: {
      fontFamily: {
        display: ["Playfair Display", "Georgia", "serif"],
        body: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "monospace"],
        "headline-sm": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "label-sm": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-md": ["Playfair Display"],
        "label-md": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
      },
      colors: {
        "secondary-fixed": "#e5e2e1",
        tertiary: "#b8c8da",
        "surface-variant": "#333535",
        "secondary-container": "#4a4949",
        "inverse-on-surface": "#2f3131",
        "primary-container": "#c5a059",
        "surface": "#121414",
        "tertiary-fixed": "#d4e4f6",
        "on-tertiary": "#223240",
        "primary-fixed-dim": "#e9c176",
        "on-tertiary-fixed": "#0d1d2a",
        "error-container": "#93000a",
        "on-surface-variant": "#d1c5b4",
        "surface-container": "#1e2020",
        "tertiary-container": "#97a7b8",
        "surface-container-low": "#1a1c1c",
        "on-primary": "#412d00",
        "surface-tint": "#e9c176",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-highest": "#333535",
        "on-background": "#e2e2e2",
        "on-tertiary-fixed-variant": "#394857",
        "inverse-primary": "#775a19",
        "on-secondary-container": "#bab8b7",
        "surface-dim": "#121414",
        "outline-variant": "#4e4639",
        "surface-bright": "#38393a",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#5d4201",
        "error": "#ffb4ab",
        "background": "#121414",
        "surface-container-high": "#282a2b",
        "on-error": "#690005",
        secondary: "#c8c6c5",
        "on-primary-container": "#4e3700",
        "on-secondary": "#313030",
        "on-secondary-fixed": "#1c1b1b",
        primary: "#c5a059",
        "primary-fixed": "#ffdea5",
        outline: "#9a8f80",
        "on-surface": "#e2e2e2",
        "on-primary-fixed": "#261900",
        "tertiary-fixed-dim": "#b8c8da",
        "on-tertiary-container": "#2d3d4b",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-lowest": "#0c0f0f",
        "inverse-surface": "#e2e2e2",
        danger: "#ffb4ab",
        warning: "#e9c176",
        success: "#b8c8da",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        base: "8px",
        "container-max": "1200px",
        "stack-md": "24px",
        "stack-sm": "12px",
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.3), 0 1px 2px rgba(0,0,0,0.2)",
        elevated: "0 10px 40px rgba(0,0,0,0.4)",
        barber: "0 4px 20px rgba(0,0,0,0.3)",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.32, 0.72, 0, 1)",
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          from: { opacity: "1", transform: "translateY(0)" },
          to: { opacity: "0", transform: "translateY(12px)" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-right": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(100%)" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        shimmer: "shimmer 2s infinite ease-in-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-out": "fade-out 0.3s ease-in forwards",
        "slide-in-right": "slide-in-right 0.5s var(--spring) forwards",
        "slide-out-right": "slide-out-right 0.4s var(--spring) forwards",
        "scale-in": "scale-in 0.3s var(--spring) forwards",
      },
    },
  },
  plugins: [],
};
export default config;